- dags/nci_c3_upload_s3_pathrow.py
This DAG takes row/path parameter to sync Collection 3 data from NCI to AWS S3 bucket for selected row/path region. It takes following additional runtime parameters from `dag_run.conf`:
* `pathsrows`: PathRow value of the scene. `'091089', '090089'`
* `startdate`: Start date of the scene acquisition to sync. `2006-01-01`
* `enddate`: End date of the scene acquisition to sync. `2006-12-31`
```
{
"pathsrows": "'091089', '090089'",
"startdate": "2006-01-01",
"enddate": "2006-12-31"
}
```
Here, `pathsrows` is a mandatory parameter while `startdate` and `enddate`  is optional. If provided,
syncs takes place for specified period otherwise for all available period.
> DAG to sync sample scenes based on path/row

- dags/nci_ard.py
The DAG starts `ard_scene_select` which filters the landsat L1 scenes to send to ARD to process.
It also starts the ARD processing.  ARD processing indexes the ARD output scenes.
> adding nci c3 ard processing.

- dags/nci_db_incremental_csvs.py
This DAG runs daily at 1am Canberra Time.
It dumps any changes to the ODC Database into a CSV file per table, and uploads them to
s3://nci-db-dump/csv-changes/${datestring}/
This DAG should be idempotent, ie. running repeatedly is safe.
> Upload daily database changes from NCI to S3

- dags/nci_build_dea_module.py
- dags/nci_build_dea_unstable_module.py
- dags/nci_build_env_module.py
- dags/nci_cog_and_upload.py
- dags/nci_dataset_ingest.py
- dags/nci_db_backup.py
- dags/nci_index_s2ard_simple.py
- dags/nci_wofs.py
- dags/testdag.py
- plugins/operators/ssh_operators.py
- Make COG conversion and uploading more robust (may still need more improvements)
- Make owner names consistent
- Switch more DAGs from `dea/unstable` to `dea` module
- Fix mistake when switching away from using the `dea/unstable` module to the stable one.
> Fixes and Cleanups for NCI Collection 2 Processing

- dags/nci_dataset_sync.py
The NCI is turning everything off tomorrow, and 20 hour walltimes are excessive for these dataset sync tasks.
> Shrink walltime required for NCI Sync

- README.md
- docker-compose.yml
With new documentation in the README.
Based on the default Airflow docker image, instead of the weird puckel one.
Uses environment variables to setup the Airflow Connections that our DAGs depend on.
> New Docker Compose setup for local testing

- dags/k8s_nci_db_incremental_sync.py
- Added jinja template logic to set DATESTRING runtime.
- This will allow running DAG manually to import csvs for specific date. Otherwise DAG runs everyday (schedule job) by setting DATESTRING defaults to {{ ds }}.
- To run DAG manually, please provide `DATESTRING` dagrun.config as below -
```
{ "DATESTRING": "<YYYY-MM-DD>"}
```
> add jinja template logic to set DATESTRING

- dags/k8s_nci_db_update_summary.py
comment out execution_timeout - dag still fails due to timeout -needs  to evaluate its value again and enable this config
> comment out execution_timeout - dag still fails due to timeout

- dags/k8s_wagl_nrt_ancillary.py
- delete things that are more than 2 days old
- I still do not like this solution because it leaves empty folders, but the `find` command in our containers do not seem to support the `-empty` flag
> cleanup ancillary volume

- dags/k8s_wagl_nrt.py
Instead of a DAG with 30 parallel pipelines every 30 minutes, let's do 5 parallel pipelines every 5 minutes. More DAG runs, but failures are easier to locate.
> wagl-nrt: make DAG runs more frequent

- dags/nci_cog_and_upload.py
Make it wait 3 days before failing all the successive jobs,
so that simply marking it as 'success', will continue the DAG.
> Fix COGing Manual Verification step

- dags/nci_c3_download_derivs.py
Uses:
- `s5cmd` to do a fast, full, download of the entire S3 folder structure
- Records the new files that are downloaded, and indexes them into the database
Shortcomings:
- Doesn't handle archived/deleted datasets, yet
- Not idempotent/partitioned by date, it performs a full sync every time it runs
- Syncs based on S3 Listings, not a database index or S3 Inventory. Less efficient, more costly, but plenty fast enough and not actually expensive.
> Download C3 Derivatives to the NCI

- dags/infra/images.py
- dags/k8s_index_fc_wo_c3.py
- dags/k8s_index_ls_c3.py
Yo @pindge this is needed in the OWS DB too. I think I've fixed it in all the right places.
The 0.0.16 indexing image fixes an issue with archiving datasets, FYI.
> Update the indexer image many places

- dags/k8s_aws_db_migrate_schema copy.py
- dags/k8s_nci_db_migrate_schema.py
- dags/k8s_sandbox_db_migrate_schema.py
This PR creates x3 DAG's to apply schema migrations for a given latest version of an Explorer using the `cubedash-gen --init -v` command. The 3 ODC instances in this cluster are :
- AWS S3 + Sandbox
- AWS S3 + OWS
- NCI RDS Copy
> #207 Create x3 Schema migration DAG's

- dags/sentinel_2_nbart/nbart_nci_s2_upload_s3.py
- dags/sentinel_2_nbart/upload_s2_nbart.py
This PR adds a DAG + uploader script that syncs S2 NBART data from NCI to S3. The DAG is almost identical to the [nbar dag](https://github.com/GeoscienceAustralia/dea-airflow/blob/master/dags/nci_s2_upload_s3.py), and the upload script has a few additions changes.
The upload script now:
- creates eo3 and stac metadata and uploads this to S3
- sends the stac metadata to the SNS topic "U29500-Test"
> Sentinel 2 NBART S3 Sync

- dags/nci_build_dea_module.py
The nci build dea dag fails during testing with 
```python
pytest: error: unrecognized arguments: --nbval-lax
```
This might be because running `pytest ....` uses a pytest installed in a different python environment w/ out `nbval`. This PR runs `python -m pytest ..` instead to try and fix this.
> Fix NCI Build DEA

- dags/nci_build_dea_module.py
This PR deletes the module with todays date before attempting to build the module.
For some reason my recent build didn't use the latest `dea-cogger` from https://packages.dea.ga.gov.au/dea-cogger/ so I'm re-building the module.
> Delete module for today before building

- dags/wagl/k8s_wagl_nrt.py
I kind of misunderstood what this variable means and what the pool means. The pool should be bigger than this, not smaller.
> wagl_nrt: set concurrent runs for wagl to 60

- dags/infra/images.py
leave out whitespace so as to make the xcom fit into xcom size limit
> wagl image update

- dags/infra/connections.py
using different id to avoid overriding the manual settings
> add terraform provided conn ids

- dags/k8s_dea_update_collection.py
Currently it is a lengthy manual process to refresh the collection list whenever a new collection is added. e.g. 
1. retrieve the CSV and copy in the /data folder of dea-access. 
2. Run csv2collections.py to generate the json files
3. Run the postCollectionDocker.sh to update the resto APIs.
This is all dockerized and this DAG is to enable just a simple run whenever a new collection is added to the dea-config/workspaces/collections.csv file
> add collection update dag

- dags/wagl/k8s_wagl_nrt.py
As @Kirill888 pointed out, the wagl pod asks for less resources than it can.
> bump up wagl pod resource requests

- dags/wagl/k8s_wagl_nrt.py
This reverts commit 4a3befccbf183bd16413eb4770ed0a30197eb7c7.
Nodes are not matching anymore.
> Revert "bump up wagl pod resource requests"

- dags/sentinel_2_nbart/nbart_fix_metadata.py
- dags/sentinel_2_nbart/nbart_s2b_fix_metadata.py
- scripts/upload_s2_nbart.py
This PR adds some extra properties to nbart metadata required for `alchemist`. I've tested these properties with the fixup dags and `alchemist` can now be run!
It also changes the version of the fixup dags to enable better monitoring of their progress.
Once this is merged I'll restart all nbart upload dag runs that are running to ensure a consistent state, and then run the fixup dags.
> Add extra properties

- .github/workflows/dag_lint.yaml
- .github/workflows/dag_test.yaml
- dags/utility/utility_odc_db_backup_to_s3.py
- requirements.txt
starting to migrate import path to v2 standard, this is enabled by upgrade-backporter
https://airflow.apache.org/docs/apache-airflow/stable/upgrading-to-2.html#step-4-import-operators-from-backport-providers
add to requirement.txt for real server testing and monitoring before cutting over
> Migrate utility to v2

- dags/automated_reporting/tasks/s2_completeness.py
A small fix in an automated reporting dag, issue with relative file paths to open a local resource file.
> acs_reporting: fixed issue with relative file path to aoi list file

- dags/infra/images.py
- so that we don't get any unexpected surprises while developing
> [ard] fix ARD docker image

- dags/automated_reporting/developement_dags/rep_s2_completeness_dev.py
- dags/automated_reporting/rep_expire_completeness_prod.py
- dags/automated_reporting/rep_s2_completeness_prod.py
Fixed an issue in previous PR with the incorrect kwargs being passed to s2 completeness task, and shortened task ids slightly so they display better in the UI.
> automated_reporting: fixed incorrect kwargs for s2 completeness dags

- dags/ard/k8s_ard_nrt_ancillary.py
This is a nice to have, the modtran binaries are already in our EFS, but this ensures that they will be there even if our EFS goes down for some reason.
> [ard] sync modtran

- dags/collection3/odc-db/k8s_index_s2_derivatves_odc.py
Burn vector processing pods should be deleted after execution has completed.
> Disable pod persistence.

- dags/automated_reporting/developement_dags/rep_expire_completeness_dev.py
- dags/automated_reporting/developement_dags/rep_nrt_simple_latency_dev.py
- dags/automated_reporting/developement_dags/rep_usgs_monitoring_dev.py
- dags/automated_reporting/rep_s2_completeness_prod.py
- dags/automated_reporting/rep_usgs_monitoring_prod.py
Need to use pendulum timezone instead of `datetime.timezone` more of the same as #579
> More import fixes for Airflow 2.2.2

- dags/automated_reporting/tasks/latency_from_completeness.py
- dags/automated_reporting/tasks/s2_ard_completeness.py
- dags/automated_reporting/tasks/s2_deriv_completeness.py
- dags/automated_reporting/tasks/s2_l1_completeness.py
- dags/automated_reporting/tasks/simple_latency.py
- dags/automated_reporting/tasks/sns_latency.py
- dags/automated_reporting/tasks/usgs_aquisitions.py
- dags/automated_reporting/tasks/usgs_ard_completeness.py
- dags/automated_reporting/tasks/usgs_l1_completeness.py
- dags/automated_reporting/tests/integration_tests/test_s2_completeness.py
- dags/automated_reporting/tests/integration_tests/test_usgs_completeness.py
- dags/automated_reporting/tests/misc_tests/m2m_test.py
- dags/automated_reporting/tests/misc_tests/sns_currency_test.py
This is in response to a psycopg2 error in s2 completeness monitoring which has been failing since the 2.2.2 upgrade. Fixing the deprecation warning seems to fix the error with psycopg2 when testing locally. Not sure why.
> automated_reporting: replaced next_execution_date with data_interval_end

- dags/collection3/nci_c3_download_derivs.py
Add DAG steps for downloading summary products for WOfS 
* ga_ls_wo_fq_apr_oct_3
* ga_ls_wo_fq_cyear_3
* ga_ls_wo_fq_myear_3
* ga_ls_wo_fq_nov_mar_3
and Geomedian
* ga_ls5t_nbart_gm_cyear_3
* ga_ls7e_nbart_gm_cyear_3
* ga_ls8c_nbart_gm_cyear_3
I don't think syncing these directories daily is a significant cost. 
The pricing is [$0.0055](https://aws.amazon.com/s3/pricing/) per 1,000 S3 `ListObjects`  requests. Each `LIST` request returns a [maximum of 1,000 keys](https://forums.aws.amazon.com/thread.jspa?threadID=268525).
Taking a look at the WOfS data:
```
[jm5638@gadi-login-06 ga_ls_wo_3]$ cd /g/data/jw04/ga/ga_ls_wo_3
[jm5638@gadi-login-06 ga_ls_wo_3]$ find . -type f | wc -l
2378910
```
That would be about ~$0.013 a day to list all of `ga_ls_wo_3`.
> Add NCI download DAGs for WOfS and Geomedian summary products

- dags/collection3/nci_c3_download_derivs.py
Suspend LS8 fc indexing on NCI temporarily on NCI for reprocessing. I'm sure there is a better way to do this, but it's only a temporary/once off thing.
> suspend ls8 fc indexing on nci for reprocessing

- dags/nci_aws/nci_update_explorer_tables.py
For the new [NCI Explorer](https://explorer.nci.dea.ga.gov.au/) that's actually hosted at the NCI.
So that we can get rid of our horrible kludge of a database replication system.
> Automatically update NCI Explorer Database

- dags/collection3/nci_c3_download_derivs.py
It was disabled for the reprocessing of our Landsat 8 Fractional Cover Collection 3 data a few months ago.
I've archived the old LS8 FC in the NCI Database, and run a backfill index of the data already there.
This change is required to keep the NCI index up to date with new datasets.
> Switch on indexing of LS8 FC on NCI

- constraints.txt
fixes
```
************* Module operators.ssh_operators
plugins/operators/ssh_operators.py:10:0: E0611: No name '_make_intermediate_dirs' in module 'airflow.providers.sftp.operators.sftp' (no-name-in-module)
```
> add sftp constraint

- dags/webapp_update/update_list.py
`ga_s2_wo_provisional_3` is a provisional NRT product running in dev. It's produced via an alchemist pipeline which automatically gets indexed, but Explorer and OWS also need to be updated.
> Update webapps for ga_s2_wo_provisional_3 in dev

- .pre-commit-config.yaml
- dags/automated_reporting/dea_sandbox_user_logins.py
Query Loki for the Sandbox logs of user logins, then dump them into the reporting db.
I also had issues with pre-commit trying to install `psycopg2` instead of `psycopg2-binary` and failing. :facepalm: .
> Extract sandbox logins to reporting db
