GeoscienceAustralia/dea-airflow

dags/nci_s2_upload_s3.py
docker-compose.yml
requirements.txt
scripts/s2_to_s3_rolling.py

https://gajira.atlassian.net/secure/RapidBoard.jspa?rapidView=549&projectKey=DEADM&modal=detail&selectedIssue=DEADM-1270

Added DAG and script to upload sentinel-2 data from nci to s3 bucket

---

.github/workflows/main.yml
dags/k8s_dea_access_resto_ingester.py

Please review @omad @whatnick Thank you.

Added initial k8s_dea_access_resto_ingester dag

---

dags/nci_s2_upload_s3.py
scripts/s2_to_s3_rolling.py

- Update end date of DAG `nci_s2_upload_s3 `to `2020-07-22`
- Suppressed log output to `--only-show-errors`

Updated nci_s2_upload_s3 DAG end date to 2020-07-22

---

.github/workflows/main.yml
dags/k8s_dea_access_resto_ingester.py
dags/k8s_index_s2_s3.py
dags/k8s_s3_orchestrate.py
dags/k8s_thredds_orchestrate.py

- Fixed import for K8s Secret and 
- updated airflow version to `1.10.11` in GitHub actions main.yml file
Fixes https://github.com/GeoscienceAustralia/dea-airflow/issues/31

Fix DAGs for Airflow 1.10.11

---

.github/workflows/main.yml
dags/k8s_db_sync.py
dags/k8s_index_s2_s3.py
dags/k8s_s3_orchestrate.py
dags/k8s_thredds_orchestrate.py

- Fixed K8s secret import
- JSON notation in comments
- Maintain CI to new Airflow version

Fix issues with airflow 1.10.11 upgrade

---

dags/nci_db_backup.py

Fix a bug in one of the variable names.
Also gzip the files that go to S3.

Fix DB Backup DAG error in datastring name

---

dags/nci_test_ard.py

adding ard processing, no indexing, prod DB read, non-prod file system.

adding ard processing, no indexing, prod DB read, non-prod file system.

---

dags/nci_c3_upload_s3_backlog.py
scripts/c3_to_s3_rolling.py

- Added backlog DAG and sync script to sync C3 to S3
- Syncing for initial 2 months for 3 Landsat C3 products

Add c3 to s3 backlog DAG

---

dags/nci_c3_upload_s3_backlog.py

End date updated to sync running for next 2 years

Updated end date for Landsat3 products

---

dags/nci_s2_upload_s3.py

- Added feature to read enddate from Variable for S2 to S3 sync

Read enddate from Variable

---

dags/sentinel_2_nrt/env_cfg.py
dags/sentinel_2_nrt/images.py
dags/sentinel_2_nrt/sentinel_2_nrt_archive.py
dags/sentinel_2_nrt/sentinel_2_nrt_indexing.py
dags/sentinel_2_nrt/utility_explorer_summary.py
dags/sentinel_2_nrt/utility_ows_update_extent.py

remove dummyoperator
add indexing dag
update productname
use latest indexing image

Cleanup and deploy indexing

---

.github/workflows/main.yml
.pre-commit-config.yaml
.pylintrc
README.md
import_hook.py

fix this https://github.com/GeoscienceAustralia/dea-airflow/issues/58 for master branch
also resolve pylint pythonpath setting

Add pylint to master

---

dags/nci_c3_upload_s3_backlog.py

- Complete sync of Landsat 5
- Updated sync date to 2020-07-31 for Landsat 7/8

Updated sync date to 2020-07-31

---

dags/k8s_db_sync.py
dags/k8s_db_sync_new.py

Nci db sync

---

dags/nci_c3_upload_s3.py

- Ongoing DAG added
- Update end date for backlog DAG to cover last processed date

Add Ongoing DAG/Update enddate for backlog DAG

---

dags/github_metrics.py
dags/nci_cog_and_upload.py
dags/nci_db_backup.py
dags/nci_index_s2ard.py
dags/nci_index_s2ard_simple.py

Other fixes:
- Fix the NCI COG and Upload which was broken in the last PR
- Switch to full name for specifying DAG ownership (instead of username)

Update NCI Sentinel 2 Indexing to Daily and other fixes

---

dags/k8s_nci_db_sync.py

DAG to setup nci database in sandbox environment.

DAG to setup nci database in sandbox environment

---

dags/k8s_nci_db_sync.py

- update DAG to use latest s3-to-rds image
- set `DATESTRING` environment variable

update DAG to use latest s3-to-rds image

---

dags/env_var/infra.py
dags/sentinel_2_nrt/env_cfg.py
dags/sentinel_2_nrt/images.py
dags/sentinel_2_nrt/sentinel_2_nrt_archive.py
dags/sentinel_2_nrt/sentinel_2_nrt_indexing.py
dags/sentinel_2_nrt/subdag_explorer_summary.py
dags/sentinel_2_nrt/subdag_ows_views.py
dags/sentinel_2_nrt/utility_explorer_summary.py
dags/sentinel_2_nrt/utility_ows_update_extent.py

- add more db roles
- add full suite of odc products for indexing from the same sqs 
- update image tags
- update role names

ows-data replacement for ows-db dump in sandbox cluster

---

dags/k8s_nci_db_incremental_sync.py
dags/k8s_nci_db_update_summary.py

added DAGs to perform -
- NCI db incremental sync (daily)
- NCI db update-summary (weekly)

add DAGs to perform NCI db incremental sync and update-summary

---

dags/sentinel_2_nrt/sentinel_2_nrt_batch_indexing.py
dags/sentinel_2_nrt/sentinel_2_nrt_streamline_indexing.py
dags/sentinel_2_nrt/sentinel_2_nrt_update.py

- add batch indexing for the last 3 days in case anything was missed from streamline indexing
- add ows-update and explorer-update as a dag
- remove unused imports

Add update and batch indexing

---

dags/nci_common.py
dags/nci_dataset_ingest.py
dags/nci_dataset_sync.py

Missed setting a default SSH Connection to use in the recent refactor...

Fixe wofs/fc

---

scripts/c3_to_s3_rolling.py

- Add message attribute 'maturity' in SNS message and set its value from the `dea:dataset_maturity` field.

Add message attribute 'maturity'

---

dags/nci_cog_and_upload.py
dags/nci_dataset_ingest.py
dags/nci_dataset_sync.py
dags/nci_fractional_cover.py
dags/nci_wofs.py

COG and Upload is failing due to adding/renaming one of the tasks in the DAG, and not updating the reference to it.
This means that the tasks checking to see how much work there is to do is failing.
**also**: Make sure documentation is shown for each DAG, and add links between the related DAGs to ease seeing what's going on.

Fix COG and Upload

---

dags/k8s_nci_db_incremental_sync.py
dags/k8s_nci_db_sync.py

- update s3-to-rds image to 0.1.1-unstable.49.gf1fbfbb - has fix for incremental import

update s3-to-rds image to 0.1.1-unstable.49.gf1fbfbb

---

dags/nci_cog_and_upload.py
dags/nci_common.py
dags/nci_dataset_ingest.py
dags/nci_dataset_sync.py
dags/nci_fractional_cover.py
dags/nci_wofs.py

A few tweaks after the last execution.
- Improve the 'manual check' message if required to generate an unusally large number of COGs
- Improve timeouts across the DAG
- Make it easier to manually mark if required (no need to clear following Tasks)
- Send emails to Alex, Damien and Dave on failure or manual check required

Improve Collection 2 Processing Workflow

---

dags/k8s_nci_db_incremental_sync.py
dags/k8s_nci_db_sync.py
dags/k8s_nci_db_update_summary.py

removing hard coded database name from k8s-nci-db sync dags

k8s nci db dags: read db-name from db-secrets

---

dags/k8s_index_fc_wo_c3.py
dags/k8s_index_fc_wo_c3_backlog.py

Untested. Hoping a review will catch any silly mistakes!

Add wofs and fc indexing dags to sandbox

---

dags/aws_check_dead_queues.py
dags/k8s_index_fc_wo_c3.py
dags/k8s_index_fc_wo_c3_backlog.py

* Checks dead queues for bodies
* Doesn't do anything with them except for hassle Alex

Add dead queue checker

---

dags/aws_check_dead_queues.py

* Don't send context to the DAG
* Use the conn that's sent as an arg

Fix DAG by not sending context

---

.github/workflows/main.yml

- change airflow version to `1.10.12`
- add names to each runs
- make `airflow list_dags` to load dags from this repo
- disable example dags being loaded

make airflow list_dags to load dags from this repo

---

dags/k8s_wagl_nrt_ancillary.py
dags/k8s_wagl_nrt_filter.py

- Add wagl NRT ancillary DAG (copies ancillary from other buckets into the EFS volume)
- Add wagl NRT filtering DAG (filters and keeps only Australian scenes in a separate queue)

add wagl NRT ancillary and filtering DAGs

---

dags/k8s_wagl_nrt_ancillary.py

- Ensure folders exist before running commands on them

wagl-nrt: these folders need to exist

---

dags/sqs_processing_workflow/images.py

merge after 0.0.14 image is built

Update image tags

---

dags/k8s_wagl_nrt_ancillary.py

- so no need to maintain these EFS folders
- any one approving will do, thanks

wagl now uses node storage instead of EFS

---

dags/aws_check_dead_queues.py

This fixes a silly little error in reporting.

Report the right wrong queues

---

dags/k8s_wagl_nrt.py

This DAG is currently doing processing at a 100% capacity in dev. I am just migrating it to sandbox to see what new issues arise.
The suboptimal concurrency problem still have not been solved.

wagl-nrt: turn on processing

---

dags/nci_build_dea_module.py
dags/nci_build_dea_unstable_module.py
dags/nci_build_env_module.py

- Don't email Damien every day
- Fail more quickly if any part of the shell scripts fail
- Don't bother retrying, this stuff isn't likely benefit from retries

Tweak NCI Environment builds

---

dags/k8s_index_fc_wo_c3.py
dags/k8s_index_ls_c3.py

Update Sandbox env indexing images to the latest build

Update indexing image to 0.0.15

---

dags/aws_check_dead_queues.py

Add a couple more queues to the dead queue checker.

Add Landsat Indexing and Archiving Queues to the dead queue checker

---

dags/developer_support/k8s_odc_db_backup_to_s3.py

fix dump command

---

.github/workflows/main.yml

build requirement

---

dags/k8s_index_fc_wo_c3.py

This adds S2 NRT WO indexing to the FC/WO C3 DAG. I don't know whether we'd want to rename any of this to match though, or have S2 have its own DAG.

Added S2 NRT WO indexing

---

dags/k8s_index_fc_wo_c3.py

Fixed queue name for S2 NRT WO

---

dags/k8s_index_fc_wo_c3.py

Fixed k8s_index_fc_wo_c3.py

---

dags/k8s_index_fc_wo_c3.py

Fixed fc indexing

---

dags/k8s_index_ls_c3.py

* Resolves an issue where the Archiving process would try to index after archiving, which doesn't work, resulting in 1 dataset at a time still getting archived, but a very very slow process of getting through 200 scenes.

Update indexing image to fix issue with Archiving

---

dags/nci_build_dea_unstable_module.py
dags/nci_build_env_module.py
dags/nci_c3_download_derivs.py
dags/nci_c3_upload_s3.py
dags/nci_db_backup.py
dags/nci_db_incremental_csvs.py
dags/nci_s2_upload_s3.py

Maximise signal by minimising noise.

Don't email when merely retrying a task

---

dags/sentinel_2_nrt/env_cfg.py
dags/subdags/subdag_explorer_summary.py
dags/subdags/subdag_ows_views.py
dags/utility/utility_explorer_summary.py
dags/utility/utility_ows_update_extent.py
dags/webapp_update/sentinel_2_nrt_update.py
dags/webapp_update/update_list.py

- create a dag folder called `webapp_update` for `ows` and `explorer` dedicated operations
- move ows update list out of `sentinel2` to `webapp_update`
- create a dedicated list for `explorer` update products

refactor dags

---

dags/subdags/subdag_explorer_summary.py
dags/subdags/subdag_ows_views.py
dags/utility/utility_explorer_summary.py
dags/utility/utility_ows_update_extent.py
dags/webapp_update/sentinel_2_nrt_update.py
dags/webapp_update/update_list.py

- split webapp update dag away from sentinel 2 folder
- create a dedicated webapp dag folder
- add c3 products to list of products for updating

update dag to include updating c3 products

---

dags/k8s_nci_db_incremental_sync.py

New image has sync ordering issue fixed

k8s nci sync - update s3-to-rds to use latest stable

---

dags/infra/images.py
dags/k8s_aws_db_migrate_schema.py
dags/k8s_nci_db_migrate_schema.py
dags/k8s_odc_db_migrate_schema.py
dags/k8s_sandbox_db_migrate_schema.py

Change secrets used in DB Schema updates

#207 Create schemas for all DB's

---

dags/infra/images.py
dags/k8s_migrate_nci_db_schema.py
dags/k8s_migrate_odc_db_schema.py
dags/k8s_nci_db_incremental_sync.py
dags/k8s_nci_db_sync.py
dags/k8s_nci_db_update_summary.py

use images.py to place images, update k8s DAGs accordingly

use images.py to place images, update k8s DAGs accordingly

---

dags/k8s_index_fc_wo_c3.py

* Update the production indexing DAG to match DEV

Align Sandbox with DEV in terms of C3 derivative indexing

---

dags/sentinel_2_nrt/sentinel_2_nrt_archive.py
dags/sentinel_2_nrt/sentinel_2_nrt_batch_indexing.py
dags/sentinel_2_nrt/sentinel_2_nrt_streamline_indexing.py

strict sqs to dc indexing to 1 active run per dag

strict indexing from sqs to 1 dag only

---

dags/infra/images.py
dags/infra/variables.py
dags/k8s_nci_db_incremental_sync.py
dags/k8s_nci_db_incremental_update_summary.py

NCI db prod: update to run incremental summary
This will reduce a load to database and we can run update-summary daily instead of weekly

refactor nci dbsync DAGs, added a DAG to run incremental update-summary

---

dags/k8s_nci_db_incremental_sync.py
dags/k8s_nci_db_incremental_update_summary.py
dags/k8s_nci_db_maintenance.py
dags/k8s_nci_db_sync.py
dags/k8s_nci_db_update_summary.py

executing `vacuum analyze` to nci db every second day. this will optimise the database and improve performance for nci explorer

added a maintenance DAG for nci database

---

dags/utility/utility_index_from_s3.py

This might work, but it probably won't. I need some k8s to test it.

Add utility indexing dag

---

dags/webapp_update/update_list.py

Added S2 (NRT) WO

---

dags/infra/iam_roles.py
dags/infra/images.py
dags/infra/podconfig.py
dags/infra/pools.py
dags/infra/s3_buckets.py
dags/infra/sqs_queue.py
dags/infra/variables.py
dags/k8s_wagl_nrt.py
dags/k8s_wagl_nrt_ancillary.py
dags/k8s_wagl_nrt_filter.py
dags/sentinel_2_nrt/sentinel_2_nrt_archive.py
dags/sentinel_2_nrt/sentinel_2_nrt_batch_indexing.py
dags/sentinel_2_nrt/sentinel_2_nrt_streamline_indexing.py
dags/subdags/subdag_explorer_summary.py
dags/subdags/subdag_ows_views.py
dags/utility/utility_odc_db_backup_to_s3.py

- split variables file preventing it to grow too big
- update dags to import from correct file.

split from variables

---

dags/k8s_wagl_nrt.py

Follows Alchemist in interacting with SQS (finally, yay!)

wagl_nrt: sync dev and prod

---

dags/collection3/k8s_index_fc_wo_odc.py
dags/collection3/k8s_index_ls_c3_odc.py
dags/infra/README.md
dags/infra/iam_roles.py
dags/infra/pools.py
dags/infra/s3_buckets.py
dags/infra/sqs_queues.py
dags/infra/variables.py
dags/k8s_nci_db_incremental_sync.py
dags/sentinel_2_nrt/sentinel_2_nrt_streamline_indexing.py
dags/utility/utility_odc_db_backup_to_s3.py
dags/wagl/k8s_wagl_nrt.py
dags/wagl/k8s_wagl_nrt_ancillary.py
dags/wagl/k8s_wagl_nrt_filter.py

reduce the size of infra.variables.

refactor infra

---

dags/k8s_dea_access_dataloader.py

replace owner

---

dags/infra/connections.py
dags/infra/iam_roles.py
dags/infra/s3_buckets.py
dags/infra/sqs_queue.py
dags/infra/variables.py

- add audit check date to docstring
- either add the variables via teraform or remove
- for review for decision
- add odc reader conn id

add audit check

---

dags/collection3/k8s_index_fc_wo_odc.py
dags/collection3/k8s_index_ls_c3_odc.py
dags/infra/connections.py
dags/infra/iam_roles.py
dags/infra/s3_buckets.py
dags/infra/sqs_queues.py
dags/infra/variables.py
dags/sentinel_2_nrt/sentinel_2_nrt_archive.py
dags/sentinel_2_nrt/sentinel_2_nrt_batch_indexing.py
dags/sentinel_2_nrt/sentinel_2_nrt_streamline_indexing.py
dags/utility/qa_report/terraform_var_conn_check.py
dags/utility/utility_annual_workflow.py
dags/utility/utility_explorer_summary.py
dags/utility/utility_odc_db_backup_to_s3.py
dags/utility/utility_ows_update_extent.py
dags/webapp_update/sentinel_2_nrt_update.py
scripts/c3_to_s3_rolling.py

- add declared in infra variables but not supplied by terraform
- add more variables supplied by terraform but not declared
- update dag to use `region` directly instead of get from secret
- rename variables for clarity
- remove the use of svc secret but to use iamroles for indexing
- setup qa reporting dag

infra audit check

---

dags/infra/images.py

update wagl image again to fix bug

---

dags/infra/images.py
dags/wagl/k8s_wagl_nrt.py
dags/wagl/k8s_wagl_nrt_ancillary.py
dags/wagl/k8s_wagl_nrt_filter.py

- simplify logic when there is nothing to be done

wagl_nrt: update wagl image (change in dataset yaml format)

---

dags/infra/images.py

I think my python script is not flushing stdout.

wagl_nrt: wagl docker image update

---

dags/nci_build_dea_module.py
dags/nci_build_dea_unstable_module.py
dags/nci_build_env_module.py

The three modified DAGs are utilities for creating new dea software environments on the NCI.
See Also: https://github.com/GeoscienceAustralia/digitalearthau/pull/288

Update for moved NCI Environment setup code

---

dags/infra/variables.py
dags/k8s_index_c3_backlog.py
dags/k8s_index_c3_wo_fc_backlog.py
dags/k8s_index_fc_wo_c3.py
dags/k8s_index_ls_c3.py
dags/sentinel_2_nbart/k8s_index_s2_nbart.py
dags/utility/utility_index_from_s3.py

- align c3 dags to use infra variables `odc-writer` and `db_hostname`
- move c3 hardcoded secret to infra variables for sustainment purposes
- add `ondemand_node_affinity` to all c3 k8soperators.

refactor c3

---

dags/infra/connections.py
dags/nci_aws/k8s_nci_db_incremental_sync.py
dags/nci_aws/k8s_nci_db_sync.py
dags/nci_c3_upload_s3.py
dags/nci_c3_upload_s3_backlog.py
dags/nci_c3_upload_s3_pathrow.py
dags/nci_db_log_report.py
dags/sentinel_2_nbart/nbart_nci_s2_upload_s3.py
dags/wagl/k8s_wagl_nrt.py
dags/wagl/k8s_wagl_nrt_filter.py

- fix conn id typo
- update all dags referencing to connection ids created  via web UI to use terraform created (all visible from UI)
- update hardcoded reference to `svc` to use infra. roles
- other fixes for lint

update dags to use terraform created connections 

---

README.md

Update docs to use specific version of airflow.

Pin Airflow version to be used in docs

---

dags/k8s_dea_access_resto_ingester.py

add secrets as env

---

dags/infra/connections.py
dags/rep_nrt_simple_latency.py

Updated dag to insert to reporting db

Nc134 s2 nrt reporting dag

---

dags/automated_reporting/helpers.py
dags/automated_reporting/rep_nrt_completeness.py
dags/automated_reporting/schemas.py
dags/automated_reporting/sql.py
dags/automated_reporting/tasks.py
dags/infra/connections.py
dags/infra/variables.py

This is an early version of this dag to test odc and copernicus api queries. No inserts into reporting db yet.

Nc113 s2 nrt completeness

---

.gitignore
docker-compose.yml

Not sure if this is the best way to do this, but looking for somewhere to keep tests outside of dags folder, so I can run them locally using docker.

Add volume for `tests` in docker-compose.yml 

---

dags/wagl/k8s_wagl_nrt.py

Approval to switch target from the dev bucket to the prod bucket.
**DO NOT MERGE**: I will merge at an opportune moment when the traffic is slow.

Sentinel-2 NRT switchover

---

dags/utility/utility_add_product.py

- takes `product_definition_uri` and `product_name`
- run `datacube product add {{uri}}`
- add it to explorer.

add product dag

---

dags/infra/images.py
dags/wagl/k8s_wagl_nrt_poc.py

Initial commit with baseline settings

---

dags/wagl/k8s_wagl_nrt_ancillary.py

- Add more stuff (ancillaries in HDF5 format) to the EFS volume for Sentinel-2 NRT

Sync new ancillaries

---

.github/workflows/dag_lint.yaml
.github/workflows/dag_test.yaml
dags/test/test_emailoperator.py
dags/testdag.py
requirements.txt

- add all backport libraries to requirements.txt

add backport to requirements

---

.github/workflows/v2_check.yaml
dags/subdags/subdag_ows_views.py
dags/utility/utility_index_from_s3.py
requirements-dev.txt

- add v2.1 airflow github action, checking against current dags
- the changes to module names can be found here https://airflow.apache.org/docs/apache-airflow/stable/extra-packages-ref.html
- fix utility dag indexing-to-s3
- update requirement-dev to `v1.10.14`

add workflow to check dags against v2.1.0 airflow

---

dags/sentinel_2_nrt/sentinel_2_nrt_streamline_indexing.py

- the latest indexer image is broken for --record-path sqs-to-dc indexing

ping indexer image

---

.github/workflows/dag_lint.yaml
dags/automated_reporting/databases/reporting_db.py

- re-enable pylint
- disable pylint error lines

Disable lint

---

dags/sentinel_2_nrt/sentinel_2_nrt_archive.py
dags/subdags/subdag_explorer_summary.py
dags/utility/utility_annual_workflow.py
dags/utility/utility_explorer_summary.py
dags/webapp_update/webapp_update.py
tests/dag_structure/test_utility_dags.py

- convert all explorer subdag to explorer_operator
- default explorer_operator xcom to be None

Rework web subdags

---

dags/sentinel_2_nrt/sentinel_2_nrt_archive.py
dags/subdags/subdag_explorer_summary.py
dags/subdags/subdag_ows_views.py
dags/utility/utility_annual_workflow.py
dags/utility/utility_explorer_summary.py
dags/utility/utility_ows_update_extent.py
dags/webapp_update/webapp_update.py
tests/dag_structure/test_utility_dags.py

- remove explorer_subdag
- convert ows subdag to ows operator
- replace ows subdag imports to ows operator

convert ows subdag to operator

---

.github/workflows/main.yml
.pre-commit-config.yaml
constraints.txt
dags/dea_utils/update_explorer_summaries.py
dags/dea_utils/update_ows_products.py
dags/nci_aws/k8s_nci_db_update_summary.py
dags/sentinel_2_nrt/sentinel_2_nrt_archive.py
dags/sentinel_2_nrt/sentinel_2_nrt_batch_indexing.py
dags/sentinel_2_nrt/sentinel_2_nrt_streamline_indexing.py
dags/subdags/podconfig.py
dags/tests/test_emailoperator.py
dags/utility/utility_annual_workflow.py
dags/utility/utility_explorer_summary.py
dags/utility/utility_ows_update_extent.py
dags/webapp_update/sentinel_2_nrt_update.py
dags/webapp_update/update_list.py
docker-compose.yml
requirements.txt
tests/test_dea_utils.py
tests/test_utility_ows_update.py

Sorry Pin, this grew a bit bigger than planned. Let me know if you want to go through it with me, we can make time on Wednesday.
In summary:
- Using the power of Airflow Templates to remove the need for custom python code and passing arguments through XCom
- Renamed the `subdag` module to `dea_utils`, and simplified and refactored the functions within.
- Added automated tests for the two functions in `dea_utils`.
- Updated all the DAGs that update OWS or Explorer to use the new features.
- Updated `requirements.txt` and `docker-compose.yml` from the `develop` branch for local testing.
- Updated `pre-commit` config to run siloed from the system install of `pylint`

Simplifying utility DAGs, cleaning up in general

---

.github/workflows/v1_dag_lint.yml
.github/workflows/v1_dag_test.yml
dags/automated_reporting/databases/reporting_db.py
dags/automated_reporting/developement_dags/rep_nrt_simple_latency_dev.py
dags/automated_reporting/tasks/__init__.py
dags/automated_reporting/tasks/s2_completeness.py
dags/collection3/sandbox-db/k8s_index_fc_wo_c3.py
dags/collection3/sandbox-db/k8s_index_fc_wo_c3_backlog.py
dags/collection3/sandbox-db/k8s_index_ls_c3.py
dags/k8s_db_sync.py
dags/nci_aws/k8s_nci_db_incremental_update_summary.py
dags/nci_aws/k8s_nci_db_maintenance.py
dags/nci_build_dea_unstable_module.py
dags/sentinel_2_nbart/k8s_index_s2_nbart.py
dags/sentinel_2_nbart/k8s_index_s2_nbart_backlog.py
dags/sentinel_2_nbart/k8s_index_s2_nbart_sandbox.py
dags/sentinel_2_nbart/k8s_index_s2_nbart_sandbox_backlog.py
dags/utility/qa_report/terraform_var_conn_check.py
dags/utility/utility_add_product.py
dags/utility/utility_explorer_summary.py
dags/wagl/k8s_wagl_nrt.py
scripts/save_github_stats.py
scripts/upload_s2_nbart.py
tests/dag_structure/test_utility_dags.py
tests/test_automated_reporting/test_usgs_completeness.py
tests/test_c3_to_s3_rolling.py

- add flake8 for F401
- add `utility_add_product`
- split ci to `lint` and `test`

add flake8 to lint F401

---

dags/ard/k8s_ard_nrt_ancillary.py
dags/ard/k8s_ard_nrt_landsat_provisional.py
dags/ard/k8s_ard_nrt_sentinel2_provisional.py
dags/infra/images.py
dags/infra/s3_buckets.py
dags/infra/sns_topics.py
dags/infra/sqs_queues.py
dags/infra/variables.py
dags/wagl/k8s_wagl_nrt_filter.py

- set up the provisional NRT product pipelines
- two DAGs, one for Sentinel-2 and one for Landsat
- the ancillary sync now has its own user

[ard] set up the provisional NRT pipeline

---

dags/ard/k8s_ard_nrt_landsat_provisional.py
dags/ard/k8s_ard_nrt_sentinel2_provisional.py
dags/infra/sqs_queues.py

[ard] fix sqs message url and s3 prefixes

---

dags/ard/k8s_ard_nrt_landsat_provisional.py
dags/ard/k8s_ard_nrt_sentinel2_provisional.py

- Add explorer URL as an argument to the docker container

[ard] STAC doc generation needs an explorer URL

---

dags/ard/k8s_ard_nrt_landsat_provisional.py
dags/ard/k8s_ard_nrt_sentinel2_provisional.py

- Enable pipelines to be run automatically on schedule

[ard] bring provisional NRT pipelines online

---

dags/sentinel_2_nrt/env_cfg.py

- start indexing the provisional NRT datasets!

[ard] index provisional NRT datasets

---

dags/infra/images.py

- pull docker image from ECR
- suffer slower development time 😄

[ard] get new wagl docker image from ECR

---

dags/ard/k8s_ard_nrt_sentinel2_provisional.py

[ard] sentinel-2 sns refactor (publishes from container now)

---

dags/dea_utils/update_explorer_summaries.py
dags/utility/utility_explorer_summary.py

- change dag_run to be flag like 
- add recreate-extent flag

add changes

---

dags/infra/images.py
dags/webapp_update/update_list.py

- update ows to latest tagged image
- add new provisional nrt to web update list

add s2_nrt_provisional_granule_nbar_t to webupdate

---

dags/utility/utility_add_product.py

add --update-if-exists

---

.github/workflows/deletion_dag_test.yaml
dags/deletion/deletion_sql_queries.py
dags/deletion/utility_delete_dataset_location.py
dags/utility/utility_datacube_product_update.py

- add delete dataset location dag
- update naming in dags
- update docs

add location delete dag

---

dags/deletion/utility_delete_dataset_location.py
dags/deletion/utility_delete_odc_product.py
dags/deletion/utility_delete_selected_years_datasets.py
dags/infra/variables.py

- add ows-admin and explorer-admin secret for delete product dag
- update deletion dags tagging for consistency
- add delete product dag

add delete product dag

---

dags/ard/k8s_ard_nrt_ancillary.py

- port the GQA ancillary and reference images sync from develop

[ard] sync GQA ancillaries

---

dags/ard/k8s_ard_nrt_sentinel2.py
dags/infra/sns_topics.py
dags/infra/sqs_queues.py

Although this PR does not re-enable the legacy NRT pipeline, it gets ready for something like that.
The structure of the DAG is a lot simpler now that the copying is done in a lambda and not here.

[ard] clean up legacy Sentinel-2 NRT DAG

---

.flake8
.github/workflows/v2_check.yaml
dags/automated_reporting/developement_dags/rep_asb_google_analytics_dev.py
dags/automated_reporting/developement_dags/rep_expire_completeness_dev.py
dags/automated_reporting/developement_dags/rep_nrt_simple_latency_dev.py
dags/automated_reporting/developement_dags/rep_s2_completeness_dev.py
dags/automated_reporting/developement_dags/rep_usgs_monitoring_dev.py
dags/automated_reporting/rep_expire_completeness_prod.py
dags/automated_reporting/rep_nrt_simple_latency_prod.py
dags/automated_reporting/rep_s2_completeness_prod.py
dags/automated_reporting/rep_usgs_monitoring_prod.py

First attempt at k8spodoperator. Welcome feedback, particularly on the passing in of Airflow variables and secrets.

automated_reporting: asb google analytics stats - DEV DB

---

dags/utility/utility_add_product.py
dags/utility/utility_annual_workflow.py

- pin index image version
- add `flags` conf  and remove hard-coded flags
- change `s3-to-dc` command structure to dedent

improve dag

---

dags/automated_reporting/rep_expire_completeness_prod.py
dags/automated_reporting/rep_nrt_simple_latency_prod.py

After the upgrade to 2.2.2, we started getting an error. This should fix it.

Fix DAG import errors in Airflow 2.2.2

---

dags/automated_reporting/rep_asb_google_analytics_prod.py

This a change to recompute the Aus Seabed usage stats back to Jun 2020.

automated_reporting: recompute auseabed google analytics stats

---

dags/automated_reporting/developement_dags/rep_s3_storage_stats.py
dags/infra/variables.py

Add DAG for aws s3 storage stats and the related variables.

Nemo 2317 s3 storage stats

---

dags/automated_reporting/developement_dags/rep_s3_storage_stats.py

bump version to 1.2.50
Modify the tag to be in alignment with other reporting-dev DAGs

fix db conn for dev

---

dags/automated_reporting/developement_dags/rep_s3_storage_stats.py

rename dag to be in alignment with other automated reporting dags

---

dags/automated_reporting/developement_dags/rep_s3_storage_stats.py

Add schedule and start date for s3 storage stats DAG

Nemo 2317 add schedule

---

dags/automated_reporting/rep_s3_storage_stats.py
dags/infra/variables.py

Copy of the DAG under development dag. The secret points to the master DB. This will be the main DAG for this whole exercise. Tag is "reporting".

Nemo 2317 master db

---

dags/automated_reporting/developement_dags/rep_sara_history.py
dags/infra/variables.py

sara history DAG under development_dags. This to test connectivity and processing/updates to "develop" DB

sara history dags under master branch/sandbox airflow

---

dags/k8s_waterbodies_conflux.py

update dea waterbodies conflux dag to include doco examples and link to dea search doco

ConfluxDagBex

---

dags/automated_reporting/developement_dags/rep_sara_history.py

Bump version to 1.2.54 to address a date issue.

bump version to 1.2.54

---

dags/automated_reporting/rep_sara_history.py

Nemo 2420 prod dag

---

dags/automated_reporting/developement_dags/rep_sara_history.py

Add archie steps for nci monthly stats dag

Nemo 2317 archie

---

dags/automated_reporting/developement_dags/rep_sara_history.py

fix a typo in the function name

fix a typo in the function name

---

dags/automated_reporting/rep_cophub_monthly_prod.py

Add archie ingestion/aggregation tasks to nci_monthly_prod dag

add archie to nci monthly prod dag

---

dags/automated_reporting/developement_dags/rep_sara_history.py

fj7 storage task added to nci monthly dag in airflow sandbox connecting to dev database.

add fj7 storage disk usage to nci monthly dag

---

dags/automated_reporting/rep_cophub_monthly_prod.py

fj7 disk storage added to nci montly dag

add fj7 disk storage to nci montly dag

---

dags/automated_reporting/rep_cophub_monthly_prod.py

bump version to 1.5.1 to address fj7 storage issue.

bump version to 1.5.1 to fix fj7 storage issues

---

.github/workflows/v2_check.yaml
.gitignore
dags/collection3/nci_c3_download_derivs.py
dags/collection3/nci_c3_upload_s3.py

- Landcover Classification
- Mangrove Summary
- Tasseled Cap Percentile

Sync more summary products to NCI

---

dags/automated_reporting/rep_esa_monitoring_prod.py

replace PyPi with docker image v2.4.4

---

dags/collection3/odc-db/k8s_index_fc_wo_c3_backlog_odc.py
dags/collection3/odc-db/k8s_index_ls_c3_backlog_odc.py
dags/collection3/odc-db/k8s_index_ls_c3_odc.py
dags/collection3/odc-db/k8s_index_s2_derivatves_odc.py
dags/collection3/odc-db/k8s_index_wo_fc_c3_odc.py
dags/deletion/utility_delete_odc_product.py
dags/infra/variables.py
dags/sentinel_2_nbart/k8s_index_s2_nbart.py
dags/sentinel_2_nbart/k8s_index_s2_nbart_backlog.py
dags/sentinel_2_nrt/sentinel_2_nrt_batch_indexing.py
dags/sentinel_2_nrt/sentinel_2_nrt_streamline_indexing.py
dags/utility/utility_annual_workflow.py

- setup `statsd` variable from airflow environment
- add `statsd` flag to indexing cmd
- update pod name

add statsd to indexing cmd

---

dags/sentinel_2_nrt/sentinel_2_nrt_streamline_indexing.py

Reverts GeoscienceAustralia/dea-airflow#869

Revert "pin older version of indexer"

---

.github/workflows/v2_check.yaml

remove unused connections

---

dags/webapp_update/update_list.py

Update web apps for new C3 sentinel-2 ARD product

Update dev webapps for ga_s2m_ard_3
